/**************************************************************************

Filename    :   AS3_FlashUI.h
Content     :   
Created     :   Jan, 2010
Authors     :   Sergey Sikorskiy

Copyright   :   Copyright 2011 Autodesk, Inc. All Rights reserved.

Use of this software is subject to the terms of the Autodesk license
agreement provided at the time of installation or download, or which
otherwise accompanies this software in either electronic or hard copy form.

**************************************************************************/

#ifndef INC_AS3_FlashUI_H
#define INC_AS3_FlashUI_H


#include "Abc/AS3_Abc.h"

namespace Scaleform { namespace GFx { namespace AS3 
{

class VM;

class FlashUI
{
public:
    enum StateType {sError, sBreakpoint, sPreStep, sStep};
    
public:
    FlashUI()
    : State(sError)
    , NeedToCheck(false)
    {
    }
    virtual ~FlashUI() {}
    
public:

    // Specifies the type of output that is taking place,
    // used for color-coding and selective output by GFx.
    enum OutputMessageType
    {
        Output_Message,     // Messages generated by trace().
        Output_Error,       // Exception error messages.
        Output_Warning,     // Not implemented and other warnings generated by VM.
        Output_Action       // Action trace and VM state log.
    };

    // Called to output ActionScript trace() statements.
    virtual void Output(OutputMessageType type, const char* msg) = 0;  
    
    // Called for each opcode when GFX_AS3_VERBOSE is defined.
    virtual bool OnOpCode(Abc::TCodeOffset offset) = 0;

public:
    void SetHandleBreakpoint()
    {
        SetState(sBreakpoint);
    }
    void SetHandleStep()
    {
        SetState(sPreStep);
    }
    void SetHandleError()
    {
        SetState(sError);
    }
    
public:
    StateType GetState()
    {
        return State;
    }
    bool NeedToCheckOpCode() const
    {
        return NeedToCheck;
    }

protected:
    void SetState(StateType _state)
    {
        State = _state;
    }
public:
    void SetNeedToCheckOpCode(bool flag = true)
    {
        NeedToCheck = flag;
    }
    
protected:
    StateType State;
    bool NeedToCheck;
};

}}} // namespace Scaleform { namespace GFx { namespace AS3

#endif // INC_AS3_FlashUI_H

